package com.ai.fabric.product.shopify.bridge.store.model;

public record ShopifyBridgeVectorizationSourceRecord(
    String id,
    String updatedAt,
    String title,
    String content,
    String sourceCategory,
    String documentType,
    String storefrontUrl,
    String handle,
    String vendor,
    String productType,
    String policyType,
    String metaobjectType,
    String definitionName,
    String priceRange,
    String currencyCode,
    String availability,
    String variantSummary,
    String productVariantId,
    String firstAvailableVariantId,
    String firstAvailableVariantTitle,
    Integer variantCount,
    Integer totalInventory,
    Integer availableVariantCount
) {
    public ShopifyBridgeVectorizationSourceRecord(String id,
                                                  String updatedAt,
                                                  String title,
                                                  String content,
                                                  String sourceCategory,
                                                  String documentType,
                                                  String storefrontUrl,
                                                  String handle,
                                                  String vendor,
                                                  String productType,
                                                  String policyType,
                                                  String metaobjectType,
                                                  String definitionName,
                                                  String priceRange,
                                                  String currencyCode,
                                                  String availability,
                                                  String variantSummary,
                                                  Integer variantCount,
                                                  Integer totalInventory,
                                                  Integer availableVariantCount) {
        this(
            id,
            updatedAt,
            title,
            content,
            sourceCategory,
            documentType,
            storefrontUrl,
            handle,
            vendor,
            productType,
            policyType,
            metaobjectType,
            definitionName,
            priceRange,
            currencyCode,
            availability,
            variantSummary,
            null,
            null,
            null,
            variantCount,
            totalInventory,
            availableVariantCount
        );
    }
}
