package com.ai.infrastructure.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;
import java.util.Map;

/**
 * Relationship Query Plan
 * 
 * Represents a structured plan for querying relationships between entities.
 * Generated by LLM to understand user query intent and map it to database relationships.
 * 
 * @author AI Infrastructure Team
 * @version 1.0.0
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class RelationshipQueryPlan {
    
    /**
     * The original user query
     */
    private String originalQuery;
    
    /**
     * The semantic search query (for vector search)
     */
    private String semanticQuery;
    
    /**
     * Primary entity type to search
     */
    private String primaryEntityType;
    
    /**
     * Relationship traversal paths
     * Example: [{"from": "user", "relationship": "hasDocuments", "to": "document"}]
     */
    private List<RelationshipPath> relationshipPaths;
    
    /**
     * Direct filters extracted from query
     */
    private Map<String, Object> directFilters;
    
    /**
     * Relationship-based filters
     * Example: {"user.status": "active", "project.category": "ai"}
     */
    private Map<String, Object> relationshipFilters;
    
    /**
     * Query strategy: VECTOR_ONLY, RELATIONAL_ONLY, HYBRID, RELATIONSHIP_TRAVERSAL
     */
    private QueryStrategy strategy;
    
    /**
     * Whether semantic search (vector similarity) is needed for this query.
     * Determined by LLM during query planning.
     * If true, the query will use ENHANCED mode (relational + semantic).
     * If false, the query will use STANDALONE mode (relational only).
     */
    @Builder.Default
    private Boolean needsSemanticSearch = false;
    
    /**
     * Confidence score for the plan (0.0 to 1.0)
     */
    @Builder.Default
    private Double confidence = 0.8;
    
    /**
     * Whether to include related entities in results
     */
    @Builder.Default
    private Boolean includeRelatedEntities = true;
    
    /**
     * Maximum depth for relationship traversal
     */
    @Builder.Default
    private Integer maxTraversalDepth = 2;
    
    /**
     * Relationship Path
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class RelationshipPath {
        /**
         * Source entity type
         */
        private String fromEntityType;
        
        /**
         * Relationship type/name (e.g., "hasDocuments", "belongsTo", "createdBy")
         */
        private String relationshipType;
        
        /**
         * Target entity type
         */
        private String toEntityType;
        
        /**
         * Relationship direction: FORWARD, REVERSE, BIDIRECTIONAL
         */
        private RelationshipDirection direction;
        
        /**
         * Conditions for this relationship
         */
        private Map<String, Object> conditions;
        
        /**
         * Whether this relationship is required (INNER) or optional (LEFT)
         */
        @Builder.Default
        private Boolean required = true;
    }
    
    /**
     * Query Strategy
     */
    public enum QueryStrategy {
        /**
         * Use only vector similarity search
         */
        VECTOR_ONLY,
        
        /**
         * Use only relational database queries
         */
        RELATIONAL_ONLY,
        
        /**
         * Combine vector search with relational filters
         */
        HYBRID,
        
        /**
         * Traverse relationships in relational database
         */
        RELATIONSHIP_TRAVERSAL,
        
        /**
         * Multi-step: vector search first, then enrich with relationships
         */
        VECTOR_THEN_RELATIONSHIP,
        
        /**
         * Multi-step: relational query first, then vector search on results
         */
        RELATIONSHIP_THEN_VECTOR
    }
    
    /**
     * Relationship Direction
     */
    public enum RelationshipDirection {
        /**
         * Forward: A -> B (e.g., User -> Documents)
         */
        FORWARD,
        
        /**
         * Reverse: B -> A (e.g., Documents -> User)
         */
        REVERSE,
        
        /**
         * Both directions
         */
        BIDIRECTIONAL
    }
}
