package com.ai.fabric.platform.backend.deployment.service;

public record CoolifyTargetProfileConfig(
    String baseUrl,
    String projectUuid,
    String environmentName,
    String environmentUuid,
    String serverUuid,
    String destinationUuid,
    String defaultPublicDomainSuffix,
    String apiVersionPinned,
    int deploymentPollIntervalSeconds,
    int deploymentTimeoutSeconds,
    boolean autogenerateDomain,
    boolean forceHttps,
    String defaultPortsExposes,
    String defaultHealthCheckPath,
    String defaultHealthCheckPort
) {
}
