package com.ai.fabric.platform.backend.deployment.service;

public record CoolifyCreatePublicApplicationRequest(
    String projectUuid,
    String serverUuid,
    String environmentName,
    String environmentUuid,
    String gitRepository,
    String gitBranch,
    String buildPack,
    String baseDirectory,
    String dockerfileLocation,
    String portsExposes,
    String destinationUuid,
    String name,
    String description,
    String domains,
    boolean healthCheckEnabled,
    String healthCheckPath,
    String healthCheckPort,
    boolean instantDeploy,
    boolean autoDeployEnabled,
    boolean forceHttps,
    boolean autogenerateDomain
) {
    public CoolifyCreatePublicApplicationRequest withDomains(String updatedDomains) {
        return new CoolifyCreatePublicApplicationRequest(
            projectUuid,
            serverUuid,
            environmentName,
            environmentUuid,
            gitRepository,
            gitBranch,
            buildPack,
            baseDirectory,
            dockerfileLocation,
            portsExposes,
            destinationUuid,
            name,
            description,
            updatedDomains,
            healthCheckEnabled,
            healthCheckPath,
            healthCheckPort,
            instantDeploy,
            autoDeployEnabled,
            forceHttps,
            autogenerateDomain
        );
    }
}
