package com.ai.fabric.platform.backend.deployment.service;

import com.ai.fabric.platform.backend.deployment.entity.DeploymentProviderCredentialEntity;
import com.ai.fabric.platform.backend.deployment.entity.DeploymentTargetProfileEntity;
import com.ai.fabric.platform.backend.deployment.model.DeploymentProviderPreflightSummary;
import com.ai.fabric.platform.backend.deployment.model.DeploymentProviderType;
import com.ai.fabric.platform.backend.deployment.repository.DeploymentProviderCredentialRepository;
import com.ai.fabric.platform.backend.secret.service.PlatformSecretService;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.util.StringUtils;
import org.springframework.web.server.ResponseStatusException;

import java.time.Duration;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;

@Service
public class CoolifyTargetProfileResolver {

    private static final int PREFLIGHT_ATTEMPTS = 3;
    private static final Duration PREFLIGHT_RETRY_DELAY = Duration.ofSeconds(2);

    private final DeploymentProviderCredentialRepository credentialRepository;
    private final PlatformSecretService platformSecretService;
    private final CoolifyApiClient coolifyApiClient;
    private final ObjectMapper objectMapper;

    public CoolifyTargetProfileResolver(DeploymentProviderCredentialRepository credentialRepository,
                                        PlatformSecretService platformSecretService,
                                        CoolifyApiClient coolifyApiClient,
                                        ObjectMapper objectMapper) {
        this.credentialRepository = credentialRepository;
        this.platformSecretService = platformSecretService;
        this.coolifyApiClient = coolifyApiClient;
        this.objectMapper = objectMapper;
    }

    public CoolifyConnection requireConnection(DeploymentTargetProfileEntity profile) {
        if (profile.getProviderType() != DeploymentProviderType.COOLIFY) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Target profile is not a Coolify profile: " + profile.getId());
        }
        CoolifyTargetProfileConfig config = readConfig(profile);
        if (!StringUtils.hasText(profile.getCredentialRefId())) {
            throw new ResponseStatusException(
                HttpStatus.BAD_REQUEST,
                "Coolify target profile is missing credentialRefId: " + profile.getId()
            );
        }
        DeploymentProviderCredentialEntity credential = credentialRepository.findById(profile.getCredentialRefId())
            .orElseThrow(() -> new ResponseStatusException(
                HttpStatus.BAD_REQUEST,
                "Coolify target profile is missing provider credential: " + profile.getId()
            ));
        String token = platformSecretService.resolveSecret(credential.getSecretRef());
        if (!StringUtils.hasText(token)) {
            throw new ResponseStatusException(
                HttpStatus.BAD_REQUEST,
                "Missing Coolify API token secret: " + credential.getSecretRef()
            );
        }
        return new CoolifyConnection(config.baseUrl(), token.trim(), config);
    }

    public CoolifyTargetProfileConfig readConfig(DeploymentTargetProfileEntity profile) {
        JsonNode config = readJson(profile.getProviderConfigJson());
        JsonNode resourceDefaults = readJson(profile.getResourceDefaultsJson());
        boolean customerProjectGroupingEnabled = booleanValue(resourceDefaults, "customerProjectGroupingEnabled", false);
        String baseUrl = requireText(config, "baseUrl", profile);
        return new CoolifyTargetProfileConfig(
            stripTrailingSlash(baseUrl),
            requireText(config, "projectUuid", profile),
            requireText(config, "environmentName", profile),
            customerProjectGroupingEnabled ? text(config, "environmentUuid") : requireText(config, "environmentUuid", profile),
            requireText(config, "serverUuid", profile),
            requireText(config, "destinationUuid", profile),
            text(config, "defaultPublicDomainSuffix"),
            text(config, "apiVersionPinned"),
            intValue(config, "deploymentPollIntervalSeconds", 5),
            intValue(config, "deploymentTimeoutSeconds", 600),
            booleanValue(config, "autogenerateDomain", false),
            booleanValue(config, "forceHttps", false),
            text(config, "portsExposes", "8080"),
            text(config, "healthCheckPath", "/actuator/health"),
            text(config, "healthCheckPort", "8080")
        );
    }

    public DeploymentProviderPreflightSummary preflight(DeploymentTargetProfileEntity profile) {
        Instant checkedAt = Instant.now();
        List<String> checks = new ArrayList<>();
        ObjectNode details = objectMapper.createObjectNode();
        CoolifyConnection connection = requireConnection(profile);
        details.put("baseUrl", connection.baseUrl());
        checks.add("credential_resolved");
        RuntimeException lastFailure = null;
        int attemptsUsed = 0;
        for (int attempt = 1; attempt <= PREFLIGHT_ATTEMPTS; attempt++) {
            attemptsUsed = attempt;
            try {
                if (attempt > 1) {
                    checks.add("coolify_api_retry_" + attempt);
                }
                String version = coolifyApiClient.version(connection);
                checks.add("version_endpoint_ok");
                checks.add("version_endpoint_used_for_liveness");
                details.put("attempts", attempt);
                details.put("projectUuid", connection.config().projectUuid());
                details.put("environmentUuid", connection.config().environmentUuid());
                details.put("serverUuid", connection.config().serverUuid());
                details.put("destinationUuid", connection.config().destinationUuid());
                if (StringUtils.hasText(connection.config().apiVersionPinned())
                    && !connection.config().apiVersionPinned().equals(version)) {
                    checks.add("version_pin_mismatch");
                    return new DeploymentProviderPreflightSummary(
                        profile.getId(),
                        profile.getProviderType(),
                        "WARNING",
                        "Coolify is reachable, but the live version does not match the pinned target profile version.",
                        connection.baseUrl(),
                        version,
                        List.copyOf(checks),
                        details,
                        checkedAt
                    );
                }
                return new DeploymentProviderPreflightSummary(
                    profile.getId(),
                    profile.getProviderType(),
                    "PASSED",
                    "Coolify API version endpoint is reachable and credentials are valid.",
                    connection.baseUrl(),
                    version,
                    List.copyOf(checks),
                    details,
                    checkedAt
                );
            } catch (RuntimeException ex) {
                lastFailure = ex;
                if (!isTransientPreflightFailure(ex) || attempt == PREFLIGHT_ATTEMPTS) {
                    break;
                }
                sleepPreflightRetry();
            }
        }
        checks.add("coolify_api_failed");
        details.put("attempts", attemptsUsed);
        details.put("errorType", lastFailure == null ? "RuntimeException" : lastFailure.getClass().getSimpleName());
        return new DeploymentProviderPreflightSummary(
            profile.getId(),
            profile.getProviderType(),
            "FAILED",
            lastFailure == null ? "Coolify API preflight failed." : lastFailure.getMessage(),
            connection.baseUrl(),
            null,
            List.copyOf(checks),
            details,
            checkedAt
        );
    }

    private boolean isTransientPreflightFailure(RuntimeException ex) {
        if (ex instanceof CoolifyApiException coolifyApiException) {
            int statusCode = coolifyApiException.statusCode();
            return statusCode == 502 || statusCode == 503 || statusCode == 504;
        }
        return false;
    }

    private void sleepPreflightRetry() {
        try {
            Thread.sleep(PREFLIGHT_RETRY_DELAY.toMillis());
        } catch (InterruptedException ex) {
            Thread.currentThread().interrupt();
            throw new IllegalStateException("Interrupted while retrying Coolify preflight.", ex);
        }
    }

    private JsonNode readJson(String json) {
        try {
            return objectMapper.readTree(json == null || json.isBlank() ? "{}" : json);
        } catch (Exception ex) {
            throw new IllegalStateException("Failed to read Coolify target profile JSON.", ex);
        }
    }

    private String requireText(JsonNode config, String field, DeploymentTargetProfileEntity profile) {
        String value = text(config, field);
        if (!StringUtils.hasText(value)) {
            throw new ResponseStatusException(
                HttpStatus.BAD_REQUEST,
                "Coolify target profile " + profile.getId() + " is missing providerConfigJson." + field
            );
        }
        return value;
    }

    private String text(JsonNode config, String field) {
        return text(config, field, null);
    }

    private String text(JsonNode config, String field, String fallback) {
        String value = config.path(field).asText(null);
        return StringUtils.hasText(value) ? value.trim() : fallback;
    }

    private int intValue(JsonNode config, String field, int fallback) {
        return config.path(field).canConvertToInt() ? config.path(field).asInt(fallback) : fallback;
    }

    private boolean booleanValue(JsonNode config, String field, boolean fallback) {
        return config.has(field) ? config.path(field).asBoolean(fallback) : fallback;
    }

    private String stripTrailingSlash(String value) {
        String normalized = value.trim();
        return normalized.endsWith("/") ? normalized.substring(0, normalized.length() - 1) : normalized;
    }
}
