package com.ai.fabric.platform.backend.deployment.service;

public record CoolifyCreateDockerImageApplicationRequest(
    String projectUuid,
    String serverUuid,
    String environmentName,
    String environmentUuid,
    String imageRepository,
    String imageTag,
    String portsExposes,
    String destinationUuid,
    String name,
    String description,
    String domains,
    boolean healthCheckEnabled,
    String healthCheckPath,
    String healthCheckPort,
    CoolifyApplicationRuntimeSettings runtimeSettings,
    boolean instantDeploy,
    boolean forceHttps,
    boolean autogenerateDomain
) {
    public CoolifyCreateDockerImageApplicationRequest(
        String projectUuid,
        String serverUuid,
        String environmentName,
        String environmentUuid,
        String imageRepository,
        String imageTag,
        String portsExposes,
        String destinationUuid,
        String name,
        String description,
        String domains,
        boolean healthCheckEnabled,
        String healthCheckPath,
        String healthCheckPort,
        boolean instantDeploy,
        boolean forceHttps,
        boolean autogenerateDomain
    ) {
        this(
            projectUuid,
            serverUuid,
            environmentName,
            environmentUuid,
            imageRepository,
            imageTag,
            portsExposes,
            destinationUuid,
            name,
            description,
            domains,
            healthCheckEnabled,
            healthCheckPath,
            healthCheckPort,
            null,
            instantDeploy,
            forceHttps,
            autogenerateDomain
        );
    }
}
