package com.ai.fabric.platform.backend.marketplace.model;

import java.util.List;

public record PlatformManagedInferenceServiceSummary(
    String id,
    String serviceRef,
    String displayName,
    String serviceKind,
    String deploymentMode,
    String providerType,
    String protocolType,
    String modelId,
    String environmentScope,
    String tierScope,
    String deploymentId,
    String railwayProjectId,
    String railwayEnvironmentId,
    String railwayServiceId,
    Integer desiredReplicas,
    Integer actualReplicas,
    Integer minReplicas,
    Integer maxReplicas,
    String autoscalingMode,
    String baseUrl,
    String privateNetworkUrl,
    String healthPath,
    String secretName,
    String status,
    boolean secretConfigured,
    String lastDeploymentId,
    String lastReconciledAt,
    String lastReconcileStatus,
    String lastReconcileMessage,
    String lastHealthyAt,
    String lastProbeAt,
    String lastSuccessfulProbeAt,
    String lastFailedProbeAt,
    String lastProbeStatus,
    String lastProbeMessage,
    String driftStatus,
    String driftMessage,
    int dependentDeploymentsCount,
    int dependentActiveDeploymentsCount,
    List<PlatformManagedInferenceEndpointSummary> endpoints
) {
}
