package com.ai.infrastructure.it;

import com.ai.infrastructure.entity.AISearchableEntity;
import com.ai.infrastructure.repository.AISearchableEntityRepository;
import com.ai.infrastructure.service.AICapabilityService;
import com.ai.infrastructure.it.entity.TestProduct;
import com.ai.infrastructure.it.repository.TestProductRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Real API Integration Test for AI Infrastructure Module
 * 
 * Tests with actual OpenAI API calls to verify:
 * - Real embedding generation
 * - AI content analysis
 * - End-to-end AI processing pipeline
 * 
 * Requires OPENAI_API_KEY environment variable to be set.
 * 
 * @author AI Infrastructure Team
 * @version 1.0.0
 */
@SpringBootTest(classes = TestApplication.class)
@ActiveProfiles("real-api-test")
@Transactional
@EnabledIfEnvironmentVariable(named = "OPENAI_API_KEY", matches = "sk-.*")
public class RealAPIIntegrationTest {

    @Autowired
    private AICapabilityService capabilityService;

    @Autowired
    private AISearchableEntityRepository searchRepository;

    @Autowired
    private TestProductRepository productRepository;

    @BeforeEach
    public void setUp() {
        // Clean up before each test
        searchRepository.deleteAll();
        productRepository.deleteAll();
    }

    @Test
    public void testRealOpenAIEmbeddingGeneration() {
        System.out.println("🚀 Testing Real OpenAI Embedding Generation...");
        
        // Given - Create a product with rich content for embedding
        TestProduct product = TestProduct.builder()
            .name("AI-Powered Smart Home Hub")
            .description("Revolutionary smart home hub that uses artificial intelligence to learn your habits, optimize energy usage, and provide personalized automation. Features include voice control, predictive maintenance, and seamless integration with 100+ smart devices.")
            .category("Smart Home")
            .brand("FutureTech")
            .price(new BigDecimal("399.99"))
            .sku("SH-AI-2024")
            .stockQuantity(100)
            .active(true)
            .build();

        // When - Save and process with real AI
        product = productRepository.save(product);
        capabilityService.processEntityForAI(product, "test-product");

        // Then - Verify real AI processing
        List<AISearchableEntity> entities = searchRepository.findByEntityType("test-product");
        assertEquals(1, entities.size(), "Should process one product");

        AISearchableEntity entity = entities.get(0);
        
        // Verify embeddings were generated by real OpenAI API
        assertNotNull(entity.getEmbeddings(), "Should have embeddings from OpenAI");
        assertFalse(entity.getEmbeddings().isEmpty(), "Embeddings should not be empty");
        assertTrue(entity.getEmbeddings().size() >= 1000, "Should have substantial embeddings (text-embedding-3-small produces 1536 dimensions)");
        
        // Verify searchable content was processed
        assertNotNull(entity.getSearchableContent(), "Should have searchable content");
        assertTrue(entity.getSearchableContent().length() > 100, "Should have substantial searchable content");
        assertTrue(entity.getSearchableContent().contains("AI-Powered"), "Should contain product name");
        assertTrue(entity.getSearchableContent().contains("artificial intelligence"), "Should contain AI-related content");
        assertTrue(entity.getSearchableContent().contains("smart home"), "Should contain category content");

        // Verify metadata
        assertNotNull(entity.getMetadata(), "Should have metadata");
        assertTrue(entity.getMetadata().contains("category"), "Should have category metadata");
        assertTrue(entity.getMetadata().contains("brand"), "Should have brand metadata");
        assertTrue(entity.getMetadata().contains("price"), "Should have price metadata");

        System.out.println("✅ Real OpenAI Embedding Generation Test Passed");
        System.out.println("   - Embeddings generated: " + entity.getEmbeddings().size() + " dimensions");
        System.out.println("   - Searchable content length: " + entity.getSearchableContent().length());
        System.out.println("   - Metadata length: " + entity.getMetadata().length());
        System.out.println("   - First few embeddings: " + entity.getEmbeddings().subList(0, Math.min(5, entity.getEmbeddings().size())));
    }

    @Test
    public void testRealAIContentAnalysis() {
        System.out.println("🧠 Testing Real AI Content Analysis...");
        
        // Given - Create multiple products with different AI-related content
        List<TestProduct> products = List.of(
            TestProduct.builder()
                .name("Machine Learning Development Kit")
                .description("Complete toolkit for building and deploying machine learning models with pre-trained algorithms and cloud integration")
                .category("Development Tools")
                .brand("MLCorp")
                .price(new BigDecimal("299.99"))
                .active(true)
                .build(),
            TestProduct.builder()
                .name("Traditional Calculator")
                .description("Basic calculator for simple arithmetic operations")
                .category("Office Supplies")
                .brand("CalcInc")
                .price(new BigDecimal("19.99"))
                .active(true)
                .build(),
            TestProduct.builder()
                .name("AI-Powered Analytics Platform")
                .description("Advanced analytics platform that uses artificial intelligence to provide insights, predictions, and automated reporting")
                .category("Software")
                .brand("DataAI")
                .price(new BigDecimal("999.99"))
                .active(true)
                .build()
        );

        // When - Process all products with real AI
        products = productRepository.saveAll(products);
        for (TestProduct product : products) {
            capabilityService.processEntityForAI(product, "test-product");
        }

        // Then - Verify AI can distinguish between AI and non-AI content
        List<AISearchableEntity> allEntities = searchRepository.findByEntityType("test-product");
        assertEquals(3, allEntities.size(), "Should process all three products");

        // Search for AI-related content - should find 2 products
        List<AISearchableEntity> aiResults = searchRepository.findBySearchableContentContainingIgnoreCase("artificial intelligence");
        assertTrue(aiResults.size() >= 1, "Should find AI-related content");

        // Search for machine learning content
        List<AISearchableEntity> mlResults = searchRepository.findBySearchableContentContainingIgnoreCase("machine learning");
        assertTrue(mlResults.size() >= 1, "Should find machine learning content");

        // Search for analytics content
        List<AISearchableEntity> analyticsResults = searchRepository.findBySearchableContentContainingIgnoreCase("analytics");
        assertTrue(analyticsResults.size() >= 1, "Should find analytics content");

        // Verify each entity has proper embeddings
        for (AISearchableEntity entity : allEntities) {
            assertNotNull(entity.getEmbeddings(), "Each entity should have embeddings");
            assertTrue(entity.getEmbeddings().size() >= 1000, "Each entity should have substantial embeddings");
            assertNotNull(entity.getSearchableContent(), "Each entity should have searchable content");
            assertTrue(entity.getSearchableContent().length() > 50, "Each entity should have substantial content");
        }

        System.out.println("✅ Real AI Content Analysis Test Passed");
        System.out.println("   - Total products processed: " + allEntities.size());
        System.out.println("   - AI-related results: " + aiResults.size());
        System.out.println("   - ML-related results: " + mlResults.size());
        System.out.println("   - Analytics results: " + analyticsResults.size());
    }

    @Test
    public void testRealAISemanticSearch() {
        System.out.println("🔍 Testing Real AI Semantic Search...");
        
        // Given - Create products with semantically similar but different wording
        List<TestProduct> products = List.of(
            TestProduct.builder()
                .name("Wireless Bluetooth Headphones")
                .description("High-quality wireless headphones with noise cancellation and long battery life")
                .category("Audio")
                .brand("SoundTech")
                .price(new BigDecimal("199.99"))
                .active(true)
                .build(),
            TestProduct.builder()
                .name("Cordless Audio Earpieces")
                .description("Premium cordless earpieces featuring active noise reduction and extended playtime")
                .category("Audio")
                .brand("AudioPro")
                .price(new BigDecimal("249.99"))
                .active(true)
                .build(),
            TestProduct.builder()
                .name("Gaming Keyboard")
                .description("Mechanical gaming keyboard with RGB lighting and programmable keys")
                .category("Gaming")
                .brand("GameTech")
                .price(new BigDecimal("149.99"))
                .active(true)
                .build()
        );

        // When - Process all products
        products = productRepository.saveAll(products);
        for (TestProduct product : products) {
            capabilityService.processEntityForAI(product, "test-product");
        }

        // Then - Test semantic search capabilities
        List<AISearchableEntity> allEntities = searchRepository.findByEntityType("test-product");
        assertEquals(3, allEntities.size(), "Should process all three products");

        // Search for audio-related content (should find both headphones and earpieces)
        List<AISearchableEntity> audioResults = searchRepository.findBySearchableContentContainingIgnoreCase("audio");
        assertTrue(audioResults.size() >= 2, "Should find audio-related products");

        // Search for wireless content (should find both wireless products)
        List<AISearchableEntity> wirelessResults = searchRepository.findBySearchableContentContainingIgnoreCase("wireless");
        assertTrue(wirelessResults.size() >= 1, "Should find wireless products");

        // Search for gaming content (should find only gaming keyboard)
        List<AISearchableEntity> gamingResults = searchRepository.findBySearchableContentContainingIgnoreCase("gaming");
        assertTrue(gamingResults.size() >= 1, "Should find gaming products");

        System.out.println("✅ Real AI Semantic Search Test Passed");
        System.out.println("   - Total products: " + allEntities.size());
        System.out.println("   - Audio results: " + audioResults.size());
        System.out.println("   - Wireless results: " + wirelessResults.size());
        System.out.println("   - Gaming results: " + gamingResults.size());
    }

    @Test
    public void testRealAIEndToEndWorkflow() {
        System.out.println("🔄 Testing Real AI End-to-End Workflow...");
        
        // Given - Create a comprehensive product catalog
        List<TestProduct> catalog = List.of(
            TestProduct.builder()
                .name("AI-Powered Fitness Tracker")
                .description("Smart fitness tracker with AI-driven health insights, workout recommendations, and sleep analysis")
                .category("Wearables")
                .brand("FitAI")
                .price(new BigDecimal("199.99"))
                .active(true)
                .build(),
            TestProduct.builder()
                .name("Smart Home Security System")
                .description("Complete home security system with AI-powered facial recognition and motion detection")
                .category("Security")
                .brand("SecureHome")
                .price(new BigDecimal("599.99"))
                .active(true)
                .build(),
            TestProduct.builder()
                .name("Traditional Desk Lamp")
                .description("Simple desk lamp with adjustable brightness")
                .category("Furniture")
                .brand("LightCorp")
                .price(new BigDecimal("49.99"))
                .active(true)
                .build()
        );

        // When - Process entire catalog
        catalog = productRepository.saveAll(catalog);
        for (TestProduct product : catalog) {
            capabilityService.processEntityForAI(product, "test-product");
        }

        // Then - Verify comprehensive AI processing
        List<AISearchableEntity> allEntities = searchRepository.findByEntityType("test-product");
        assertEquals(3, allEntities.size(), "Should process all catalog items");

        // Verify all entities have proper AI processing
        for (AISearchableEntity entity : allEntities) {
            assertNotNull(entity.getEmbeddings(), "Each entity should have embeddings");
            assertTrue(entity.getEmbeddings().size() >= 1000, "Each entity should have substantial embeddings");
            assertNotNull(entity.getSearchableContent(), "Each entity should have searchable content");
            assertTrue(entity.getSearchableContent().length() > 50, "Each entity should have substantial content");
            assertNotNull(entity.getMetadata(), "Each entity should have metadata");
            assertNotNull(entity.getCreatedAt(), "Each entity should have creation timestamp");
        }

        // Test various search scenarios
        List<AISearchableEntity> aiResults = searchRepository.findBySearchableContentContainingIgnoreCase("AI");
        assertTrue(aiResults.size() >= 2, "Should find AI-related products");

        List<AISearchableEntity> smartResults = searchRepository.findBySearchableContentContainingIgnoreCase("smart");
        assertTrue(smartResults.size() >= 2, "Should find smart products");

        List<AISearchableEntity> securityResults = searchRepository.findBySearchableContentContainingIgnoreCase("security");
        assertTrue(securityResults.size() >= 1, "Should find security products");

        System.out.println("✅ Real AI End-to-End Workflow Test Passed");
        System.out.println("   - Catalog items processed: " + allEntities.size());
        System.out.println("   - AI-related products: " + aiResults.size());
        System.out.println("   - Smart products: " + smartResults.size());
        System.out.println("   - Security products: " + securityResults.size());
        System.out.println("   - Average embeddings per product: " + (allEntities.stream().mapToInt(e -> e.getEmbeddings().size()).sum() / allEntities.size()));
    }
}