CREATE TABLE IF NOT EXISTS ai_behavior_insights (
  id UUID PRIMARY KEY,
  user_id VARCHAR(255) UNIQUE NOT NULL,
  segment VARCHAR(100),
  patterns CLOB,
  recommendations CLOB,
  insights CLOB,
  sentiment_score DOUBLE,
  sentiment_label VARCHAR(50),
  churn_risk DOUBLE,
  churn_reason TEXT,
  previous_sentiment_score DOUBLE,
  previous_churn_risk DOUBLE,
  trend VARCHAR(50),
  analyzed_at TIMESTAMP,
  confidence DOUBLE,
  ai_model_used VARCHAR(100),
  model_prompt_version VARCHAR(20),
  processing_time_ms BIGINT,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS app_behavior_event (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id VARCHAR(255) NOT NULL,
  event_type VARCHAR(120) NOT NULL,
  event_timestamp TIMESTAMP NOT NULL,
  event_data CLOB,
  source VARCHAR(120)
);

CREATE INDEX IF NOT EXISTS idx_app_behavior_event_user_ts ON app_behavior_event(user_id, event_timestamp);

