client_id = "939df746e3bbbb0a8ab2f31cf94bd11b"
name = "Loom Companion"
handle = "loom-companion"
application_url = "https://shopify-bridge.loomai.pro"
embedded = true
extension_directories = ["extensions/*"]
web_directories = [".", "ui"]

[access_scopes]
scopes = "read_products,read_content,read_legal_policies,read_metaobjects,read_metaobject_definitions,read_orders,customer_read_customers,customer_read_orders,customer_write_orders,customer_read_store_credit_accounts"

[auth]
redirect_urls = [
  "https://shopify-bridge.loomai.pro/auth/shopify/callback"
]

[customer_authentication]
redirect_uris = [
  "https://shopify-bridge.loomai.pro/api/customer-auth/callback"
]
javascript_origins = [
  "https://shopify-bridge.loomai.pro"
]

[build]
automatically_update_urls_on_dev = false
dev_store_url = "https://shopping-companion-test.myshopify.com"

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
name = "loom-companion-compliance"
compliance_topics = [
  "customers/data_request",
  "customers/redact",
  "shop/redact"
]
uri = "/api/webhooks/shopify"

[app_proxy]
url = "https://shopify-bridge.loomai.pro"
subpath = "loom-companion"
prefix = "apps"
