create table if not exists shopify_companion_package_profiles (
    id varchar(64) primary key,
    profile_key varchar(64) not null unique,
    package_key varchar(64) not null,
    tier_key varchar(64) not null,
    runtime_profile_key varchar(64) not null,
    vector_profile_key varchar(64) not null,
    display_name varchar(255) not null,
    description text,
    cost_posture varchar(64) not null,
    template_plugin_id varchar(128) not null,
    template_plugin_version varchar(64),
    deployment_template_id varchar(128) not null,
    inference_plugin_id varchar(128) not null,
    vector_strategy varchar(64) not null,
    vector_provisioning_mode varchar(64) not null,
    vector_storage_posture varchar(64) not null,
    verification_pack_id varchar(128) not null,
    status varchar(64) not null,
    details_json text not null default '{}',
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create index if not exists idx_shopify_companion_package_profiles_package
    on shopify_companion_package_profiles(package_key, tier_key, status);

insert into shopify_companion_package_profiles (
    id,
    profile_key,
    package_key,
    tier_key,
    runtime_profile_key,
    vector_profile_key,
    display_name,
    description,
    cost_posture,
    template_plugin_id,
    template_plugin_version,
    deployment_template_id,
    inference_plugin_id,
    vector_strategy,
    vector_provisioning_mode,
    vector_storage_posture,
    verification_pack_id,
    status,
    details_json,
    created_at,
    updated_at
)
select
    'scp-low-cost',
    'LOW_COST',
    'FREE',
    'FREE',
    'LOW_COST',
    'QDRANT_SHARED',
    'Low cost',
    'Lowest-cost Shopify Companion profile. Keeps retrieval economical and leaves advanced paid surfaces locked behind package reconciliation.',
    'LOW',
    'mkp-template-shopify-companion',
    null,
    'dev-openai-qdrant',
    'mkp-inference-local-embeddings',
    'qdrant',
    'EXTERNAL_EXISTING',
    'SHARED',
    'shopify-companion-free-readiness',
    'ACTIVE',
    '{"merchantVisible":true,"requiresBilling":false,"requiresReindexOnEmbeddingChange":true}',
    current_timestamp,
    current_timestamp
where not exists (select 1 from shopify_companion_package_profiles where profile_key = 'LOW_COST');

insert into shopify_companion_package_profiles (
    id,
    profile_key,
    package_key,
    tier_key,
    runtime_profile_key,
    vector_profile_key,
    display_name,
    description,
    cost_posture,
    template_plugin_id,
    template_plugin_version,
    deployment_template_id,
    inference_plugin_id,
    vector_strategy,
    vector_provisioning_mode,
    vector_storage_posture,
    verification_pack_id,
    status,
    details_json,
    created_at,
    updated_at
)
select
    'scp-balanced',
    'BALANCED',
    'STARTER',
    'STARTER',
    'BALANCED',
    'QDRANT_SHARED',
    'Balanced',
    'Default Shopify Companion profile. Uses the current shared embedding posture and Starter-ready source/surface boundaries.',
    'STANDARD',
    'mkp-template-shopify-companion',
    null,
    'dev-openai-qdrant',
    'mkp-inference-shared-embeddings',
    'qdrant',
    'EXTERNAL_EXISTING',
    'SHARED',
    'starter-launch-readiness',
    'ACTIVE',
    '{"merchantVisible":true,"requiresBilling":false,"requiresReindexOnEmbeddingChange":false}',
    current_timestamp,
    current_timestamp
where not exists (select 1 from shopify_companion_package_profiles where profile_key = 'BALANCED');

insert into shopify_companion_package_profiles (
    id,
    profile_key,
    package_key,
    tier_key,
    runtime_profile_key,
    vector_profile_key,
    display_name,
    description,
    cost_posture,
    template_plugin_id,
    template_plugin_version,
    deployment_template_id,
    inference_plugin_id,
    vector_strategy,
    vector_provisioning_mode,
    vector_storage_posture,
    verification_pack_id,
    status,
    details_json,
    created_at,
    updated_at
)
select
    'scp-high-quality',
    'HIGH_QUALITY',
    'ELITE',
    'ELITE',
    'HIGH_QUALITY',
    'QDRANT_SHARED',
    'High quality',
    'Higher-quality generation and embedding posture for Elite stores. Profile changes require fresh vectorization evidence.',
    'HIGH',
    'mkp-template-shopify-companion',
    null,
    'dev-openai-qdrant',
    'mkp-inference-premium-hybrid',
    'qdrant',
    'EXTERNAL_EXISTING',
    'SHARED',
    'shopify-companion-elite-readiness',
    'ACTIVE',
    '{"merchantVisible":true,"requiresBilling":true,"requiresReindexOnEmbeddingChange":true}',
    current_timestamp,
    current_timestamp
where not exists (select 1 from shopify_companion_package_profiles where profile_key = 'HIGH_QUALITY');

insert into shopify_companion_package_profiles (
    id,
    profile_key,
    package_key,
    tier_key,
    runtime_profile_key,
    vector_profile_key,
    display_name,
    description,
    cost_posture,
    template_plugin_id,
    template_plugin_version,
    deployment_template_id,
    inference_plugin_id,
    vector_strategy,
    vector_provisioning_mode,
    vector_storage_posture,
    verification_pack_id,
    status,
    details_json,
    created_at,
    updated_at
)
select
    'scp-enterprise-dedicated',
    'ENTERPRISE_DEDICATED',
    'ENTERPRISE',
    'ELITE',
    'ENTERPRISE_DEDICATED',
    'QDRANT_DEDICATED',
    'Enterprise dedicated',
    'Enterprise posture reserved for dedicated runtime/vector topology. The current catalog records the intent and keeps activation governed by operator policy.',
    'ENTERPRISE',
    'mkp-template-shopify-companion',
    null,
    'dev-openai-qdrant',
    'mkp-inference-dedicated-embedding-worker',
    'qdrant',
    'PLATFORM_MANAGED',
    'DEDICATED',
    'shopify-companion-enterprise-readiness',
    'ACTIVE',
    '{"merchantVisible":false,"requiresBilling":true,"requiresOperatorApproval":true,"requiresReindexOnEmbeddingChange":true}',
    current_timestamp,
    current_timestamp
where not exists (select 1 from shopify_companion_package_profiles where profile_key = 'ENTERPRISE_DEDICATED');

create table if not exists shopify_store_provisioning_jobs (
    id varchar(64) primary key,
    shop_domain varchar(255) not null,
    store_connection_id varchar(64),
    job_type varchar(64) not null,
    status varchar(64) not null,
    phase varchar(64) not null,
    requested_package_key varchar(64),
    requested_tier_key varchar(64),
    requested_runtime_profile_key varchar(64),
    requested_vector_profile_key varchar(64),
    previous_package_key varchar(64),
    previous_runtime_profile_key varchar(64),
    previous_vector_profile_key varchar(64),
    requested_template_plugin_id varchar(128),
    requested_template_plugin_version varchar(64),
    requested_plugin_ids_json text not null default '[]',
    profile_change_strategy varchar(64),
    vector_reindex_required boolean not null default false,
    install_intent_id varchar(128),
    attempt_count integer not null default 0,
    max_attempts integer not null default 5,
    lease_owner varchar(128),
    lease_expires_at timestamp with time zone,
    last_error_code varchar(128),
    last_error_message text,
    bootstrap_deployment_id varchar(128),
    verification_run_id varchar(128),
    next_action text,
    summary_message text,
    ready_at timestamp with time zone,
    failed_at timestamp with time zone,
    cancelled_at timestamp with time zone,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint fk_shopify_store_provisioning_jobs_store
        foreign key (store_connection_id) references shopify_store_connections(id)
);

create index if not exists idx_shopify_store_provisioning_jobs_shop_created
    on shopify_store_provisioning_jobs(shop_domain, created_at desc);

create index if not exists idx_shopify_store_provisioning_jobs_status_phase
    on shopify_store_provisioning_jobs(status, phase, created_at asc);

create index if not exists idx_shopify_store_provisioning_jobs_lease
    on shopify_store_provisioning_jobs(status, lease_expires_at, created_at asc);
