package com.ai.fabric.platform.backend.productservice.model;

public record PlatformManagedProductServiceSummary(
    String id,
    String serviceRef,
    String displayName,
    String productFamily,
    String serviceKind,
    String deploymentMode,
    String tenantMode,
    String environmentScope,
    String deploymentId,
    String railwayProjectId,
    String railwayEnvironmentId,
    String railwayServiceId,
    Integer desiredReplicas,
    Integer actualReplicas,
    Integer minReplicas,
    Integer maxReplicas,
    String baseUrl,
    String privateNetworkUrl,
    String healthPath,
    String serviceRoot,
    String dockerfilePath,
    String secretName,
    String status,
    boolean secretConfigured,
    String lastDeploymentId,
    String lastReconciledAt,
    String lastReconcileStatus,
    String lastReconcileMessage,
    String lastHealthyAt,
    String lastProbeAt,
    String lastSuccessfulProbeAt,
    String lastFailedProbeAt,
    String lastProbeStatus,
    String lastProbeMessage,
    String lastVerifiedOperation,
    String lastVerifiedAt,
    String lastVerifiedStatus,
    String lastVerifiedMessage,
    String driftStatus,
    String driftMessage,
    int dependentStoresCount,
    int activeDependentStoresCount
) {
}

