ai-entities:
  document:
    indexing:
      enabled: true
      max-characters: 8000
    analysis:
      enabled: false
      after: []
    searchable-fields:
      - name: content
        destinations: [SEMANTIC_SEARCH, RAG_CONTEXT]
        preprocessing: CLEAN
        priority: 100
        required: true
